from enum import Enum


class RunStatus(str, Enum):
    RUNNING = "RUNNING"
    SUCCESS = "SUCCESS"
    PARTIAL_SUCCESS = "PARTIAL_SUCCESS"
    FAILED = "FAILED"


class FileStatus(str, Enum):
    DETECTED = "DETECTED"
    STAGED = "STAGED"
    VALIDATING = "VALIDATING"
    REJECTED_LAYOUT = "REJECTED_LAYOUT"
    VALIDATED = "VALIDATED"
    PROCESSING = "PROCESSING"
    PREPARED = "PREPARED"
    LOADING = "LOADING"
    LOADED = "LOADED"
    PENDING_BACKUP = "PENDING_BACKUP"
    BACKED_UP = "BACKED_UP"
    PENDING_SOURCE_DELETE = "PENDING_SOURCE_DELETE"
    SUCCESS = "SUCCESS"
    FAILED = "FAILED"
    SKIPPED_ALREADY_PROCESSED = "SKIPPED_ALREADY_PROCESSED"


class ErrorCategory(str, Enum):
    FILE_QUALITY = "FILE_QUALITY"
    RECORD_QUALITY = "RECORD_QUALITY"
    INFRASTRUCTURE = "INFRASTRUCTURE"
    CONTROL = "CONTROL"


class ErrorCode(str, Enum):
    INVALID_FILENAME = "INVALID_FILENAME"
    EMPTY_FILE = "EMPTY_FILE"
    INVALID_HEADER = "INVALID_HEADER"
    INVALID_COLUMN_COUNT = "INVALID_COLUMN_COUNT"

    INVALID_EMAIL = "INVALID_EMAIL"
    INVALID_DATE_FORMAT = "INVALID_DATE_FORMAT"
    INVALID_DATE_VALUE = "INVALID_DATE_VALUE"
    INVALID_INTEGER = "INVALID_INTEGER"

    SFTP_CONNECTION_ERROR = "SFTP_CONNECTION_ERROR"
    SFTP_DOWNLOAD_ERROR = "SFTP_DOWNLOAD_ERROR"
    DATABASE_CONNECTION_ERROR = "DATABASE_CONNECTION_ERROR"
    DATABASE_LOAD_ERROR = "DATABASE_LOAD_ERROR"
    BACKUP_ERROR = "BACKUP_ERROR"
    SFTP_DELETE_ERROR = "SFTP_DELETE_ERROR"

    ALREADY_PROCESSED = "ALREADY_PROCESSED"
    CHECKSUM_MISMATCH = "CHECKSUM_MISMATCH"
    RECONCILIATION_ERROR = "RECONCILIATION_ERROR"